name: CI Lint and Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Step 3: Install ESLint for development
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint with Reviewdog
      - name: Run linting
        run: npm run lint

      # Step 5: Run tests
      - name: Run tests
        run: npm test
